
import type { Metadata } from 'next'
import { Layout, Space, ConfigProvider } from 'antd'

import '@/app/globals.css'
import HeaderCustom from '@/components/Header/HeaderCustom'
import FooterCustom from '@/components/Footer/FooterCustom'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
import Container from '@/components/Container'
import theme from '@/theme/themeConfig'


export const metadata: Metadata = {
    title: 'Dandelion',
    description: 'Generated by XiaoJiuDev',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {


    return (
        <html lang="en">
            <body className="">
                <StyledComponentsRegistry >
                    <ConfigProvider theme={theme}>
                        <Space direction="vertical" style={{ width: '100%' }} size={[0, 48]}>
                            <Layout className='bg-primary-50'>
                                <HeaderCustom />
                                <Container>
                                    {children}
                                </Container>
                                <FooterCustom />
                            </Layout>
                        </Space>
                    </ConfigProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
