import type { Metadata } from 'next'
import { ConfigProvider, Space, Layout } from 'antd'
import theme from '@/theme/themeConfig'

import StyledComponentsRegistry from '@/lib/AntdRegistry'
import '@/app/globals.css'

export const metadata: Metadata = {
    title: 'Dandelion',
    description: 'Generated by XiaoJiuDev',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className=''>
                <StyledComponentsRegistry >
                    <ConfigProvider theme={theme}>
                            {children}
                    </ConfigProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    )
}
